require("dotenv").config();

const {
  EMAIL,
  FORGET_PASSWORD_OTP_SECRET_MESSAGE,
  LOGIN_OTP_SECRET_MESSAGE,
  SIGNUP_OTP_SECRET_MESSAGE,
  SIGNUP_SECRET_MESSAGE,
  MONGO_DB_URL,
  PASSWORD,
  PORT,
  SECRET_KEY,
} = process.env;

module.exports = {
  EMAIL,
  FORGET_PASSWORD_OTP_SECRET_MESSAGE,
  LOGIN_OTP_SECRET_MESSAGE,
  SIGNUP_OTP_SECRET_MESSAGE,
  SIGNUP_SECRET_MESSAGE,
  MONGO_DB_URL,
  PASSWORD,
  PORT,
  SECRET_KEY,
};
